- name: Collecting Facts
  hosts: local 
  gather_facts: yes

- name: Setting up development environment
  hosts: local 
  roles:
    - common
    - git
    - {role: package_manager, tags: ['bootstrap']}
    - {role: zsh, tags: ['bootstrap']}
    - vim
    - python
    - node
    - zsh-autoenv
    - tmux
    - git-flow
    - jrnl
    - mycli
    - openconnect
    - mutt
    - java
    - fzf
    - cscope
    - ctags
