# Installation and setup
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

# Configuration
- name: Check if zshrc already exists
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest="{{dotfiles_user_home}}/.oh-my-zsh"

- name: Cloning zsh-autosuggestions
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    dest="{{dotfiles_user_home}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Cloning zsh-syntax-highlighting
  git:
    repo=https://github.com/zsh-users/zsh-syntax-highlighting
    dest="{{dotfiles_user_home}}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

# - import_tasks: prezto.yml
#  when: zsh_prezto

- name: Copy minimal zshrc
  copy: src=zshrc_minimal dest={{dotfiles_user_home}}/.zshrc
