# INSTALL
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

# [TODO] INSTALL PLUGIN MANAGER

# CONFIG
- name: Check if vimrc exists
  stat: path="{{dotfiles_user_home}}/.vimrc"
  register: vimrc_stat
  failed_when: False
- name: Backup vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: Symlink vimrc
  file:
    src: "{{ dotfiles_home }}/roles/vim/files/vimrc"
    dest: "{{dotfiles_user_home}}/.vimrc"
    state: link

- name: Prep vim plugin dir
  command: mkdir -p "{{dotfiles_user_home}}/.vim/plugin/"

- name: Symlink cscope_maps.vim
  file:
    src: "{{ dotfiles_home }}/roles/vim/files/cscope_maps.vim"
    dest: "{{dotfiles_user_home}}/.vim/plugin/cscope_maps.vim"
    state: link

  #- name: Install plugins
  #  command: vim +PluginInstall +qall
